
export const GET_NETFLIX_ORIGINALS="GET_NETFLIX_ORIGINALS";
export const GET_TRENDING_MOVIES="GET_TRENDING_MOVIES";
export const GET_TOPRATED_MOVIES="GET_TOPRATED_MOVIES";
export const GET_ACTION_MOVIES="GET_ACTION_MOVIES";
export const GET_COMEDY_MOVIES="GET_COMEDY_MOVIES";
export const GET_HORROR_MOVIES="GET_HORROR_MOVIES";
export const GET_ROMANCE_MOVIES="GET_ROMANCE_MOVIES";
export const GET_DOCUMENTARIES="GET_DOCUMENTARIES";
export const GET_SEARCH_MOVIE="GET_SEARCH_MOVIE";
export const SET_MOVIE_DETAIL ="SET_MOVIE_DETAIL";

export const FC_GET_NETFLIX_ORIGINALS = data => {
    return {
        type: GET_NETFLIX_ORIGINALS,
        payload: data
    };
};